language: ruby
env:
  CODECLIMATE_REPO_TOKEN: a8789f8ca71f52cc879c1fa313d94547c9a0ddbd207977fe997f686a71e0c400
  CC_TEST_REPORTER_ID: a8789f8ca71f52cc879c1fa313d94547c9a0ddbd207977fe997f686a71e0c400
rvm:
  - 2.3.4
addons:
  firefox: "49.0"
  postgresql: "9.6"
services:
  - postgresql
before_script:
  # Setup codeclimate test coverage reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # setup database
  - cp config/database.yml.travis spec/dummy/config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  # install Geckodriver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  # run Firefox
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - bin/rails db:migrate RAILS_ENV=test
  - bundle exec rspec
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT